PetCategory.create([ {name: "イヌ"},
                     {name: "ネコ"},
                     {name: "鳥"},
                     {name: "ウサギ"},
                     {name: "ハムスター"},
                     {name: "リス"},
                     {name: "フェレット"},
                     {name: "ハリネズミ"},
                     {name: "モルモット"},
                     {name: "チンチラ"},
                     {name: "モモンガ"},
                     {name: "ブタ"},
                     {name: "サル"},
                     {name: "爬虫類"},
                     {name: "その他"} ])